"""Single-experiment command line entrypoint."""

import argparse

from .config import ExperimentConfig
from .experiment import run_experiment

def parse_args() -> ExperimentConfig:
    parser = argparse.ArgumentParser(description="PADRE reproduction with a TCN backbone.")
    parser.add_argument("--data-path", required=True)
    parser.add_argument("--horizon", type=int, required=True, choices=[24, 48, 96])
    parser.add_argument("--lookback", type=int, default=60)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument(
        "--backbone",
        choices=["tcn", "nlinear", "mlp", "dlinear", "patchtst", "itransformer"],
        default="tcn",
    )
    parser.add_argument("--no-time-features", action="store_false", dest="time_features")
    parser.set_defaults(time_features=True)
    parser.add_argument("--hidden", type=int, default=32)
    parser.add_argument("--levels", type=int, default=3)
    parser.add_argument("--kernel-size", type=int, default=3)
    parser.add_argument("--tcn-head", choices=["last", "summary", "flatten"], default="last")
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--d-model", type=int, default=64)
    parser.add_argument("--n-heads", type=int, default=4)
    parser.add_argument("--transformer-layers", type=int, default=2)
    parser.add_argument("--transformer-ff", type=int, default=128)
    parser.add_argument("--itransformer-token-mode", choices=["all", "target_context"], default="all")
    parser.add_argument("--linear-skip", action="store_true")
    parser.add_argument("--patch-len", type=int, default=16)
    parser.add_argument("--patch-stride", type=int, default=8)
    parser.add_argument("--patch-individual-heads", action="store_true")
    parser.add_argument("--no-revin", action="store_false", dest="revin")
    parser.set_defaults(revin=True)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--pretrain-epochs", type=int, default=12)
    parser.add_argument("--pretrain-lr", type=float, default=1e-3)
    parser.add_argument("--pretrain-loss", choices=["mse", "smooth_l1"], default="mse")
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--online-lr", type=float, default=2e-4)
    parser.add_argument("--online-weight-decay", type=float, default=0.0)
    parser.add_argument("--policy-lr", type=float, default=1e-3)
    parser.add_argument("--policy-weight-decay", type=float, default=1e-5)
    parser.add_argument("--policy-update-interval", type=int, default=1)
    parser.add_argument("--policy-gain-scale", type=float, default=1.0)
    parser.add_argument("--gate-floor", type=float, default=0.0)
    parser.add_argument("--gate-cap", type=float, default=1.0)
    parser.add_argument("--area-gate-scale", type=float, default=0.0)
    parser.add_argument("--online-update-stride", type=int, default=1)
    parser.add_argument("--online-batch-size", type=int, default=1)
    parser.add_argument("--online-loss", choices=["mse", "smooth_l1"], default="mse")
    parser.add_argument("--online-train-scope", choices=["all", "head"], default="all")
    parser.add_argument("--residual-correction", type=float, default=0.0)
    parser.add_argument("--replay-size", type=int, default=256)
    parser.add_argument("--warmup-val-online", action="store_true")
    parser.add_argument("--emb-dim", type=int, default=32)
    parser.add_argument("--drift-dim", type=int, default=32)
    parser.add_argument("--policy-hidden", type=int, default=64)
    parser.add_argument("--pattern-epochs", type=int, default=0)
    parser.add_argument("--pattern-lr", type=float, default=1e-3)
    parser.add_argument("--k-clusters", type=int, default=4)
    parser.add_argument("--pattern-temperature", type=float, default=0.5)
    parser.add_argument("--pattern-residual-correction", type=float, default=0.0)
    parser.add_argument("--pattern-residual-feature-mode", choices=["encoded", "stats"], default="encoded")
    parser.add_argument("--adapter-weight", type=float, default=0.0)
    parser.add_argument("--adapter-lr", type=float, default=1e-3)
    parser.add_argument("--adapter-hidden", type=int, default=64)
    parser.add_argument("--prediction-ema-decay", type=float, default=0.0)
    parser.add_argument("--residual-memory", type=int, default=4)
    parser.add_argument("--episodic-memory", type=int, default=128)
    parser.add_argument("--memory-threshold", type=float, default=0.65)
    parser.add_argument("--lambda-tri", type=float, default=0.02)
    parser.add_argument("--grad-clip", type=float, default=1.0)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--limit-online", type=int, default=0)
    parser.add_argument("--offline-only", action="store_true")
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--results-dir", default="results")
    parser.add_argument("--save-model", action="store_true")
    ns = parser.parse_args()
    return ExperimentConfig(**vars(ns))


def main() -> None:
    cfg = parse_args()
    run_experiment(cfg)
